name: Deploy DsaWuerfelApp
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      - run: dotnet publish DsaWuerfelApp/DsaWuerfelApp/DsaWuerfelApp.csproj -c Release -o ./publish
      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./publish/*"
          target: "/var/www/dsawuerfelapp"
          strip_components: 1
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sqlite_native="/var/www/dsawuerfelapp/runtimes/linux-x64/native/libe_sqlite3.so"
            sudo test -f /usr/lib/x86_64-linux-gnu/libsqlite3.so.0
            sudo rm -f "$sqlite_native"
            sudo ln -s /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 "$sqlite_native"
            sudo systemctl daemon-reload
            sudo systemctl restart dsawuerfelapp.service
